### ISSUE TITLE
[Request] Option to disable film cover on lockscreen

### ISSUE THREAD

**Issue by c727** [ov3rk1ll/KinoCast#11]
^

**Comment by ov3rk1ll** [comment]
This has been added in [v1.5.5](https://github.com/ov3rk1ll/KinoCast/releases/tag/v1.5.5).

**Comment by c727** [comment]
Danke.
Das als Bild als "Videosteuerung" zu bezeichnen ist etwas irreführend. Außerdem braucht es einen App-Neustart, bevor es übernommen wird
