### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by krmax44** [ov3rk1ll/KinoCast#12]
The standard url `http://www.kinox.sg` does not work for me - using `https://kinox.tv` worked (note the https!)

**Comment by ov3rk1ll** [comment]
kinox.sg added a cloudflare ddos protection (JS based) which killed the crawler.
.to and .tv don't work in all countries so I've added Google DNS to fix this.
(see c0ea641c89a050b594ce915d5f77e6ddc288f1c1 and d4a794584f3f1ec915a0656a4809a0c38333f41d)

**Comment by krmax44** [comment]
Okay, seems to work.
