### ISSUE TITLE
Can't connect to kinox.to

### ISSUE THREAD

**Issue by MinecraftTechnicLP** [ov3rk1ll/KinoCast#13]
When I try to start the, there is a dialog telling me "kinox.to antwortet nicht". The problem is, I can't get into the app itself to change the base URL because it disposes as soon as I click ok in the dialog.

**Comment by ov3rk1ll** [comment]
This has been fixed in [v1.5.5](https://github.com/ov3rk1ll/KinoCast/releases/tag/v1.5.5) and [v1.6.0](https://github.com/ov3rk1ll/KinoCast/releases/tag/v1.6.0).
