### ISSUE TITLE
1.4.0 crashing on Phone

### ISSUE THREAD

**Issue by teaaaa** [ov3rk1ll/KinoCast#4]
It Crashes right after I start it.
In 1.3.3 Nowvideo links are also not working.

**Comment by drbeat** [comment]
working fine for me.
try clearing app data

**Comment by teaaaa** [comment]
Maybe its just my phone but still crashes. Even when I restart my phone etc Samstag, 05 März 2016, 11:48vorm. +01:00 von Mani Vazirian < notifications@github.com> :

**Comment by ivanchimeno** [comment]
Try compiling the project in Android Studio and then debugging it on your device. Maybe you can print the stack trace.

**Comment by ov3rk1ll** [comment]
Please try with today's 1.5.1 release and open a new issue if there is still a problem
