### ISSUE TITLE
Android TV navigation impossible

### ISSUE THREAD

**Issue by krmax44** [ov3rk1ll/KinoCast#6]
With Android TV and the D-Pad, the navigation is imposible. The only thing you can do is opening the hamburger menu and perform a search. No list selections possible.

**Comment by ov3rk1ll** [comment]
Hey, can you try the latests 1.5.2 build from http://bit.ly/2cnXaUx and see if that solved this problem?
I've enabled some dpad navigation but I don't have a device/TV to fully test this

**Comment by krmax44** [comment]
Menu selection works now fine, but I can't select a movie with the D-pad...

**Comment by n0sr3v** [comment]
Hey, the movie D-pad selection with the latest 1.5.2 build is working fine for me! (FireTV)
Thank you very much for your work!

**Comment by krmax44** [comment]
It's working for me now too! Awesome! Only two complains: the app does not show up in the Leanback launcher and you can't use voice search. But otherwise it's great!

**Comment by ov3rk1ll** [comment]
@krmax44 please try 1.5.3-rc1 from [here](https://dl.dropboxusercontent.com/u/35486665/Android/apk/KinoCast/com.ov3rk1ll.kinocast_v1.5.3-rc1.apk). This should add Leanback and voice search.

Since I don't have a Android TV I could only test voice search which worked fine on my phone.

**Comment by krmax44** [comment]
It shows up in the launcher now, awesome! Voice search does work on my phone, but not really on my TV. It's fine, I'll just use my phone to type it in. Thanks for putting all the stuff in the app, I appreciate it a lot!
