### ISSUE TITLE
Need your help!

### ISSUE THREAD

**Issue by ghost** [ov3rk1ll/KinoCast#7]
Hey! I am currently writing a program that gets a lot of streamcloud links as an array list. Now I want to download them all, but the problem is I just dont get it to work. I found your Streamcloud.java file but I didnt fully understand it. Could you please explain how you got the direct video url?

**Comment by ov3rk1ll** [comment]
Hey, I'll try my best to explain the StreamCloud.java file.

A Streamcloud link has 3 parts. The host, the id and the filename. You'll need the id and filename to request the playerpage which contains the full video url. The format of a link is http://streamcloud.eu/[ID]/[FILENAME].html

The script itself does this:
1. in [line 28 & 29](https://github.com/ov3rk1ll/KinoCast/blob/master/app/src/main/java/com/ov3rk1ll/kinocast/api/mirror/StreamCloud.java#L28) I take the link and get the ID and Filename by using regex
2. In [line 34](https://github.com/ov3rk1ll/KinoCast/blob/master/app/src/main/java/com/ov3rk1ll/kinocast/api/mirror/StreamCloud.java#L34) I take those to values and request the player page using the getLink function  
   This function post some required data to the url and looks for a video.mp4 link using regex
3. If the link is found on the first try we return it if not we have to wait 10 seconds and try again. Those 10 seconds are needed to bypass the capture on the site.

You can clear up the code a bit by removing all the lines starting with Log and queryTask. The getLink function can be used without any change if you build your own tool.

I hope this helps. If not, let me know what I should explain more

**Comment by ghost** [comment]
Thank you very much! With your help I managed to make it work. Now I can
auto download whole series from a site called bs.to!
