### ISSUE TITLE
[Request] Links von Hostern an KinoCast teilen

### ISSUE THREAD

**Issue by c727** [ov3rk1ll/KinoCast#8]
Hi,
Klasse App, nutze ich schon ewig :)
Manchmal sind bei kinox alle Files offline aber man findet noch Links auf Movie4k. Dann hat man zwar den NowVideo-Link aber keinen Schimmer, wie man das jetzt auf den Chromecast bekommt. (Bzw man kommt vor lauter Werbung gar nicht zum Film durch)
Es wäre super, wenn du das noch unterstützen könntest, dass man den Link aus dem Browser an Kinocast teilt und es dann abgespielt werden kann. Cover und Titel anzuzeigen wäre mir dabei unwichtig.

**Comment by ov3rk1ll** [comment]
Es gibt eine super app die genau das macht. Mit [Web Video Cast](https://play.google.com/store/apps/details?id=com.instantbits.cast.webvideo) kann man in dem eingebauten Browser einfach Links einfügen bzw gleich auf die Seite navigieren.  
In der pro variante gibt es glaub ich sogar einen adblocker ;)

KinoCast eigentlich sich wegen dem Aufbau der App nicht wirklich für so eine Funktionalität. Sowas wäre dann nur möglich, wenn Movie4k als Host in die App eingebaut wird.

**Comment by c727** [comment]
Ja, die App und ähnliche sind ganz nett.
Mein Problem scheint eher zu sein, dass sich nicht alle Files auf nowvideo streamen lassen. Scheinbar ist älteres Material flash-only... 

Aber trotzdem danke :)
